---
title: "exsnosan"
author: "Geoffrey"
date: "04/07/2021"
output: 
html_document: default
pdf_document: default
toc: TRUE
---

```{r setup, include=FALSE}
#install.packages('curl')
library(readr, dslabs)
library(tidyverse)
operations <- read_csv("https://www.data.gouv.fr/fr/datasets/r/fae6bc13-fe4c-4838-b281-b16628b7babe")
ops_stats <- read_csv("https://www.data.gouv.fr/fr/datasets/r/5d3c65fb-c861-4b22-b8aa-1eab58e3d9db")
```

# Opérations des CROSS

## nombre d'opérations par CROSS

Représentation du nombre d'opérations par CROSS, toutes années confondues

```{r distribution, echo=FALSE}

rep_par_cross <-table(operations$cross)

barplot(rep_par_cross[order(-rep_par_cross)[1:7]])
```

## Les opérations évoluent avec le temps

Distribution du nombre d'opérations par an

```{r, echo=FALSE}

personnes_par_an <- select(ops_stats,nombre_personnes_impliquees, annee ) %>% group_by(annee) %>% summarize(nbpax = sum(annee))

personnes_par_an <- as.matrix(personnes_par_an)

plot(personnes_par_an)

```

plot(personnes_par_an)

# Essai
